language: php
php:
  - 5.6

env:
  global:
    -   secure: "X8dwKmT/iLn2xeehGU76IgKqLmf3kaSmG3Xme9SjkWZpM/KeJIugxeaTFQQkmgBMvbBqkKUcMfEP2/6aNzRTxGaSs6Fuj14T3Vj2W2zp6YAkmBm9KhxOEPTsKtSNqAfw9ZQHX2syaLe++bSpEDPlIGOQ6wUAtoVub6A+xcGiMr/QHyIpx1l8iivZMmzudXbKj6onz6fa3yPM6DDzBn2U1TD7g+IuuEERFr62LrbkxbDcya+X8pjThhMNixt/u3xeRDU/bldA0irZyTMCaZl3lUVhyUJLMdav6ORO5HR2l8917WVqd9eD81KnVHqm/zPSU+85q7Ix2IBNoZHtngl+ni58f8F1H/tEgScF4ROOWObS0GwmhWFvGyfPokpeZnR8c+wmATLJ8H1Qgx+kv9aAN0GQlVJROkiRSN0D2wXQLo0EAmxPSLbuEkweSKoZPPe9BUcXHShF1XlUkHe8INtDvl4Z1HuFyUJZwuEXHMXH86cndd03yxsJTvX/coXWcvqHwCY3TsHWtWqunSLdcazPHGU2ch5giepvM/4HNzxYSimxBrZjKSEgsMi+QlHFTXkhYOSbdX+mc3NxuFsoXbYBcVqVXGnr+Q0/LgtPVInjhpMlIXwOki5uQAjks57gJJf66cV01KTpHLcZnrHgBoxFmWPCeQOyHOY+w1U33xXiUnE="

before_install:
  - composer self-update
  - export BASEDIR=${PWD}

install:
  - phpenv rehash
  - composer install
  - composer global require drush/drush:8.1.2
  - composer global require pantheon-systems/terminus
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mysql -e 'create database drupal;'

before_script:
  # This ensures that our terminus login won't hang on prompt.
  - echo "StrictHostKeyChecking no" > ~/.ssh/config

  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

  # Add our pantheon repo as an endpoint for pushes.
  - git remote add pantheon $PGIT

  # Authenticate to Terminus and pull our DB from Pantheon.
  - terminus auth login --machine-token=$MACHINETOKEN
  - terminus drush sql-dump --site=$PSITE --env=$PENV > db.sql

  # Load our downloaded DB.
  - mysql -uroot drupal < db.sql

  # Run a webserver.
  - $BASEDIR/vendor/bin/drush runserver --server=builtin 8080 --strict=0 &
  - cd ..
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done

script:
  - $BASEDIR/vendor/bin/behat

  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      git fetch pantheon &&
      git merge -m "Merge changes to pantheon from github" pantheon/master && git push origin HEAD:master &&
      git push pantheon HEAD:master;
    fi
