language: php
php:
  - 5.6

env:
  global:
    - secure: "sxC5RYvQr9PNu8HOYyNo0IcaoR+k5xWSf+jSuY62ox8S5CE3K00CaCAPzDwUwTqOgvOkaSS9jEBKE4t4747kWno2JFGTsYjvr4l/KhymkvkPtullj1bi9N51Zn9/1peEZcnNRiAYNaFrLorcVNIBG3Ip47Tjljkge5ILl7nTrNftDV/xcExDgDjeIVRshnS721cIfAV/lBm4wAVqFKvWSSPfq+5sHR7AeZRaBsXA4Im3y8+9zu5pWhyFQDxP2tDEBxJvw8P9mtF5wiWxiHlHc1Y7MQAEYTyS7uF/V7cJbLpv3LaYoYBSeOkjxbthUCRBLuolJ44EO/O/izFsbKx3TnWD/Gym96V1j13D4CP+IFDKNku10qouFQh9AqtWMiK0LAaCM/oczpqaXqP8nw1blr9T5yg80f9crS3nR8yAvw/fIjX/hniwfstmShkeOfrPS+/yIEysY8EgKoDFYg8302T40cEUt12LMwN4YuobWimY0qgXetFARnb8fd2m9H5lapLtQowNe/YZiL7eIwCiR6WfoW392h50PheJWLf8i2kU1OK6J12iANWA40TIO52wW/FR5GmBCJyZTdE0ZPH1ZIVm2BmqC0aczVNgtrSVF8prj2qA7iqt4X5FuogMIfnSMbxI2FT6TAEHYW1Sqnyu3PbDOH2o+RebdP1EpSYhWe4="

before_install:
  - composer self-update
  - export BASEDIR=${PWD}

install:
  - phpenv rehash
  - composer install
  - composer global require pantheon-systems/terminus
  - composer global require drush/drush:8.1.2
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mysql -e 'create database drupal;'

before_script:
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

  # Add our pantheon repo as an endpoint for pushes.
  - git remote add pantheon $PGIT

  # Authenticate to Terminus and pull our DB from Pantheon.
  - terminus auth login --machine-token="$MACHINETOKEN"
  - terminus drush sql-dump --site=$PSITE --env=$PENV > db.sql

  # Load our downloaded DB.
  - mysql -uroot drupal < db.sql

  # Run a webserver.
  - $BASEDIR/vendor/bin/drush runserver --server=builtin 8080 --strict=0 &
  - cd ..
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done

script:
  - $BASEDIR/vendor/bin/behat

  - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      git fetch pantheon &&
      git merge -m "Merge changes to pantheon from github" pantheon/master && git push origin HEAD:master &&
      git push pantheon HEAD:master;
    fi
